version: 0.2
env:
  parameter-store:
    AWS_ACCESS_KEY_ID: /skill-test/accesskey
    AWS_SECRET_ACCESS_KEY: /skill-test/secretkey
    ASK_VENDOR_ID: /skill-test/vendorid
    ASK_REFRESH_TOKEN: /skill-test/refreshtoken
phases:
 install:
   commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g ask-cli
      - npm install --silent --no-progress
      - npm install -g ask   
 build:
   commands:
     - |-
       if [ "$ENV_NAME" = "dev" ]; then
       echo "$ssh_key" | base64 --decode > ~/.ssh/id_rsa;
       chmod 400 ~/.ssh/id_rsa;       
       git config --global url."git@bitbucket.org:".insteadOf https://bitbucket.org/;
       git config --global url."git@bitbucket.org:".insteadOf https://sijos07@bitbucket.org/;
       git config --global url."git@github.com:".insteadOf https://github.com/;
       ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts;
       ssh-keyscan github.com >> ~/.ssh/known_hosts;
       git clone -b development git@bitbucket.org:MarkEdwardTresidder/alexa-skill.git;
       cd alexa-skill;
       env
       sed -i 's/american heart association/heart dev/g' skill-package/interactionModels/custom/en-US.json
       #Tagging Repository
       git tag Dev-$CODEBUILD_BUILD_NUMBER
       git remote set-url origin git@bitbucket.org:MarkEdwardTresidder/alexa-skill.git
       git push --tags
       fi
     - |-
       if [ "$ENV_NAME" = "qa" ]; then
       echo "$ssh_key" | base64 --decode > ~/.ssh/id_rsa;
       chmod 400 ~/.ssh/id_rsa;       
       git config --global url."git@bitbucket.org:".insteadOf https://bitbucket.org/;
       git config --global url."git@bitbucket.org:".insteadOf https://sijos07@bitbucket.org/;
       #git config --global url."git@github.com:".insteadOf https://github.com/;
       ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts;
       #ssh-keyscan github.com >> ~/.ssh/known_hosts;
       git clone -b development git@bitbucket.org:MarkEdwardTresidder/alexa-skill.git;
       cd alexa-skill;
       env
       rm -rf .ask/ask-states.json;
       cp -rf deploy/$ENV_NAME-skill.json skill-package/skill.json;
       sed -i 's/american heart association/heart stg/g' skill-package/interactionModels/custom/en-US.json
       git checkout $GIT_VERSION
       fi
     #- cp -rf deploy/$ENV_NAME-skill.json skill-package/skill.json
     - cp -r deploy/ask-states_$ENV_NAME.json .ask/ask-state.json
     - cat deploy/ask-states_$ENV_NAME.json
     #- rm -rf .ask/ask-state.json
     - mv deploy/ask-resources-code-build.json ask-resources.json
     - ask deploy
     - cat .ask/ask-states.json